---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
