---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1dg4xhac8hpz8uv77lz5ed3fphuv472j60482ru0kkwf0g6qmls2qex68ap
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1dg4xhac8hpz8uv77lz5ed3fphuv472j60482ru0kkwf0g6qmls2qex68ap
