# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:qOKS3W6GSFjJVPcwlEy9X8YEHPjdE5a1wEwogv+s3Qq5bKpS0pnNrSQeOFAtzzfBFR3Q4YBgezt9UHcGI47Tlogt3gztZHdm5jHJfJg3u017EKYDef4jwpDQS1ggMXuCN2cNQWGQkckR5skbBhfbF6Ub2VYZQi50PmouBsUb8HzNodqV7hW04fMo/oXAD9I5+iTp//T9Zt4Im76Pqjsif5A5kjQ2rulmTQRgKzI=,iv:c43krV9OPux1Qd9MYTvgC9j1yKHPciPY7xZnikmFI2E=,tag:Z4Y6sR0OLOZZnp+9B+k5sw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQUJmVW5kdWFGNEJ0cjFD
            VGdkbnNPMnRQQXpseGJzbmVDOFVpeXhXNDNZClNBNXVRSkYxYVRWam9sTHdtNDVQ
            UWQydld0Mjl2UCtKaVFjdUxkOGJocHcKLS0tIHRMYk5sOTdYZUdhL21BWUdiVUNU
            d01JQWZCMjhNN05VVThoWXpZTDBhbUUKBkrsp8/Uf0ImGLeGiY93chNHIO+aQ0s5
            sLmm0ORMRR6wSMBk60eCZf/xPqiJy3a79jzE6liU4kpZNbeoK5MQXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-15T15:38:25Z"
    mac: ENC[AES256_GCM,data:S0guC5ED6K7Mqk9ba8owAJtIuLg5gcFa6sPOxubn3YUImNtFukv0qbbnSImIV60LlVUlmrUd5Z1n8Rwq8IaBqiDnuzivMfHIUhNGXmsQrUa+N8NKoP8yWlEsmVy+E5deT7bddN/n7bfB8FVPz6sT6HgFCEXyda9l/5Rp48q5gF4=,iv:2X662T9sWWxgVzmeVQ50aR1+mSJNPyW6PODGFIGd2KU=,tag:elVcKxAtnnzmzFWj7nHbkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
