# yamllint disable
# apiVersion: v1
# kind: Secret
# metadata:
#     name: minio-helm-values
#     namespace: tools
# type: Opaque
# stringData:
#     MINIO_ROOT_PASSWORD:
#     MINIO_ROOT_USER:
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: tools
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:I9hCnsSzYZjF+lWiMDeo7zRNXX3UWiO68/g=,iv:iSjhfoI3M2vK0fowV+IILSgZIF12LvYk7zZxgVmuWsw=,tag:Vj5JGJW5V9pmpWoFwiUVAw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:D1ATenaLQNOkoCXVDvFn+oXu1uSJ25nqzms=,iv:RvDKf6GZJMUZh8ct+UqMxeb+TIItzhlm1pV77LxcrL8=,tag:KGvbrS2P0FQP7uIDwzEFIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TSsxczVrUkswVDA1NmVq
            UVZjaTM1SkxPYmdja2Flc245dWVLeTN6dUNrCms4Ykx0SHMycEJSTWdpemFXN0Yv
            NHJGSFExMVA5MllCUmJTNTI1WXJkTXcKLS0tIGJtVEVjYXVxQ1RBOUFSRUQ5ajJC
            OFVObk8xS0hHdzQyR21IZUo0UXBEdDgKIasJT3dLKOEGhYFp0LsoxoDZfOlugqY9
            7Km6F5QP10nrM26/62wFzUWcGobebzqKT9/IFlPw0iGNImAUSJF/hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-15T15:38:25Z"
    mac: ENC[AES256_GCM,data:5tBp64Lqxa5o6YHI1kMu9eZw4Uy7Mdy4eJmiHwLHO1D5qInHuxvTE2mgN7B6rhKeq9Kk1O/KLqepcpeSxGLk/PVcS8LKp6QpC43otqZCcgMtrJaoZ5NhxzEuImg/wTiyD4tA8g883fQkAJy1dsofBI5dRk29FWGQJCLuaFCS7K4=,iv:bOHiEffROl5UBwk/i4cXex+U+Ovq31e+/Qtc+fQFLI0=,tag:WWsw/y2z2Jbpq9obEHDE2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
