# yamllint disable
# apiVersion: v1
# kind: Secret
# metadata:
#     name: uptimerobot-heartbeat-url
#     namespace: monitoring
# stringData:
#     UPTIMEROBOT_HEARTBEAT_URL: https://heartbeat.uptimerobot.com/XXXXXXXXXXXXX
apiVersion: v1
kind: Secret
metadata:
    name: uptimerobot-heartbeat-url
    namespace: monitoring
stringData:
    UPTIMEROBOT_HEARTBEAT_URL: ENC[AES256_GCM,data:3Hh3vuoRA/qEqWdB2u9ASPtppusv82mGdJr6fg==,iv:h+/fsjnQSPIum88Hu3sDqTuyTmBcAzWRR4JtoruwLQg=,tag:FvacbYK4/1qQUlZusQpoiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSEFRT1F1M0ZicmpSeUJ6
            cEM4WWNnbXpxTGcvQnBIZDFvODJ6bnBYdjBvCnJoQlMwYkcrMDNtRENUTzhIdjdp
            dU1hZE90T1h0bk5BYVgzREcwQ2pIWWcKLS0tIE1iVE10RWtvdkhnVmN3ZG55TzVT
            Z1ZUc3Y0UmxScFBnZXdqVW5MeWdMcWMKeYaTuK5clkOEUrdYiRrCWTmxBI/iPc0O
            U5Bf0KNwq8n7WVVuH0yPyHyIYScHLIzyA8o6WHLFr5XO6G3dopgrRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-15T15:38:25Z"
    mac: ENC[AES256_GCM,data:AR1rP62GQtfaKEMGAGSscDXLzWGRLUX0O7G/F/QYxtcFlDjhTwGPzjh+zu8a6YJpJZDw4Rjb7UzdliFGApnSc6tgfnTfLVA4sN2Ln+TWDo8J5a918zTy9YSc16Lt8X8f3HbHJHAeEani4kJFjhVzgew8+uJz9vyMmSSSN2RJLBo=,iv:d6+mxa/q9IviDXZb8oRvAUJq7yYJUxkb/l4sH/B1U0c=,tag:H5obtuZSQ8ZBRxHWGqccKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
