# yamllint disable
# comm_config.yaml: |
#     communications:
#         discord:
#             enabled: true
#             notiftype: short
#             token:
#             botid:
#             channel:
apiVersion: v1
kind: Secret
metadata:
    name: botkube-communications
    namespace: monitoring
stringData:
    comm_config.yaml: ENC[AES256_GCM,data:V0MHD9n1wFBTQ2geTWb6rJQq9sJwOMNPtgsdRx+nXmb34MsNZoq9cWUOuuZ6KQAvU4cS5LXau8r4SPxSLscc+Hp7hJQrfxL90vaw6N6Fr2qBZ9Jbpsru6wyy+EF3oFca/2w/ZnTOl67fdCnvw9gJRn7l3RA257bd+f+Fww3nxvT8DHsm1c+TFKsyt5Irr+JnXQ==,iv:NW3WUs4lClQphRsi2utVkgjb29mH/ZcOd3D8iypBkKw=,tag:4Z7zEoFJVL1Cey2PvDRgxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cmdugn4gdwzdx9pngvtnhne5ug0u7xzxnmqxenhq5d6u9tyy05gs8879lx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydHdLWkJBSnFBVHZlMnkx
            SURGamVpbmx0SFRKdE0rakZwZzZYcTQ3UG44CkdaMTRySWNKdUFFd1Q0UXNNMUdK
            SVNTMDEwN0l6RTRQL3VKZndwclJTbXcKLS0tIHdVOGNuT01sRWx6Z2hkVWRjaDhW
            alNrUE0vcUd3bHhjYTVYWFIzUWVaS28K9Fllcehxe+6e7saZYHDncOgHadRrUk2M
            4Kv15R+RysN5nrXZAbI1fraEw+PEfOXdtHC5tvKgykRCFr88Xt6IxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-15T15:38:25Z"
    mac: ENC[AES256_GCM,data:zhcoE3eBVuQnxaSdsYcX5wKjmBGctrMv7ueUWaY/Ino9yPhirp3JX+G286GL6xWt0Da2/vr31cp6tVsfUusptc6zlYMDsxWEmQRjlDOruavFd8YCVg4sZ6d9Qmk0CTTxXGx6RG9lEJ1dS6CYHjI5N5iUnspSg8ftXBGouP6IGNI=,iv:nIyj6SYGvj1JvAD5b76jzKjlLUZSmRBqzsAqNB+G+yE=,tag:gvSJzN5FRzq3lf4ZD2wrIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
